### PR TITLE
Add more benchmark functions #158 

### PR DESCRIPTION
**Pull request by jayspeidell**
## Description
Objective Function Updates: Verified Goldstein and Booth functions working and removed TODO tags. Fixed Bulkin No 6 and removed TODO tag. Implemented Cross-in-Tray, Easom, Eggholder, Himmelblau's, Holder Table, and Three Hump Camel functions. File is getting long so I sorted the functions and added a list of functions and their corresponding function name to the docstring.

Big fix: Added 'z-axis' to formatters/Designer attribute 'labels' to prevent index out of range error when plotting in 3D.

New feature: It's hard to visualize some functions with a continuous colormap, so I added a colormaps property to the Designer class in formatters.py to allow the user to choose whichever one they want. It uses the same style as other properties of the class, and the module imports matplotlib.cm to validate both types of colormaps in matplotlib. I edited plotters/plot_countour to initialize a Designer object with a default colormap if none is provided. I've tested with every category of colormap as well as custom colormaps and verified that it is working as intended. I made the edit because I personally find it easier to understand the contrours when they use a discreet colormap. 

Default parameter change: Mesher.delta from 0.001 to 0.01. This makes it safe to run many of the functions on an average computer. With 0.001, a computer with 8GB of RAM will crash above a domain size of [8, 8] due to the size of the mesh created. Increasing by one order of magnitude allows most provided functions to run without crashing due to memory errors. 

## Related Issue
Add more benchmark functions #158

Fixing a bug: Designer only had two axis labels by default, so I added "z-axis". 

Added a feature: Designer accepts a colormap from the user. 

Changing a default parameter: The Mesher.delta parameter of 0.001 has a high chance of causing crashes to memory errors. 0.01 is safer for most of the functions in single_obj.py, but some will still crash. 

## Motivation and Context

Adding a colormap attribute to Designer made easier to verify the functions I implemented because it enabled me to use discreet colormaps. 

I fixed the range out of error bug because it caused a crash. 

I changed the default parameter of Mesher.delta because it uses a massive amount of memory. 

## How Has This Been Tested?

I created a notebook with all the added functions and tested each function as I implemented it, and then I used flask8 and black. I restricted flask8 and black testing to the files that I edited in each commit. 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
(My change doesn't need additional, but a warning for the Mesher delta attribute would help people using Pyswarms for the first time avoid memory errors.) 
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by jayspeidell** [comment]
I found the error. Can I delete my pull request?

**Comment by whzup** [comment]
If you have changes you can just push them into the branch of the pull request it will automatically synchronize. You don't have to create a new one 👍.

**Comment by whzup** [comment]
@jayspeidell By the way, make sure your commit messages fit the description in [this blog post ](https://chris.beams.io/posts/git-commit/) so our commit history is nice and uniform. To change a commit message look [here](https://help.github.com/articles/changing-a-commit-message/).
To have your changes in the development branch of the project we have to approve them in a PR and merge it afterwards just so you know how this process works 😄 .

**Comment by jayspeidell** [comment]
Cool. I'm pretty sure I've got everything together, I'm doing a new pull request now.

**Pull request closed without merging**
