### PR TITLE
Update README.md, updating methods' names

### PR DESCRIPTION
**Pull request by ewekam**
In README there were old names of properties and I updated them
- get_cost_history to cost_history
- get_pos_history to pos_history
- get_velocity_history to velocity_history
- get_mean_neighbor_history to mean_neighbor_history

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
Hi @ewekam , thanks for this! will be reviewing shortly :)

**Comment by ljvmiranda921** [comment]
@all-contributors please add @ewekam for docs

**Comment by ljvmiranda921** [comment]
Let's do this one more time, @all-contributors please add @ewekam for docs

**Comment by ewekam** [comment]
thank you!

**Pull request merged**
