### PR TITLE
Added notebook with electric circuit

### PR DESCRIPTION
**Pull request by miguelcocruz**
## Related Issue
https://github.com/ljvmiranda921/pyswarms/issues/202

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
Hi @miguelcocruz ! Thank you so much for your contribution! We will be reviewing this over the weekend or next week and merge this once everything is OK!

Have a good day!

cc: @whzup

**Comment by miguelcocruz** [comment]
Hey @ljvmiranda921 ! Thank you for the opportunity!

**Comment by miguelcocruz** [comment]
Woohoo, my first PR! 🎊 Thank you @whzup for the suggestions

**Comment by ljvmiranda921** [comment]
Hey, congratulations @miguelcocruz !
@all-contributors please add @miguelcocruz for docs and examples

**Pull request merged**
