### PR TITLE
Update feature_subset_selection.ipynb

### PR DESCRIPTION
**Pull request by diegoroman17**
Wrong objective function

## Description

Let the minimization of the objective function be the default behavior of the library. Then, If the objective is maximizing the model performance and minimize the number of features, 1-Nf/Nt is incorrect on the right term. Also, the function is wrong in the paper.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
Hi @diegoroman17 ! Thanks for this and welcome to Pyswarms! Let me review this over the weekend :)

**Comment by diegoroman17** [comment]
Hi, @ljvmiranda921 
The paper states 

> ...The goals are the maximization of model performance and the minimization of the number of used features. The objective function is defined as a fitness function (as in EA), being our goal its maximization...

> f(u_i)=\alpha(1-P)+(1-\alpha)(1-\frac{N_f}{N_t})%3D%5Calpha(1-P)%2B(1-%5Calpha)(1-%5Cfrac%7BN_f%7D%7BN_t%7D))

> where P is the performance of the model and N_f is the size of the tested feature subset

The previous function is maximized with P \rightarrow 0  and N_f \rightarrow 0. However, P \rightarrow 0 means a low performance of the model, but this is not according to the main goal. So, in my perspective the paper has an errata.

In other hand, pyswarms minimize the objective function. It is performed with P \rightarrow 1 and N_f \rightarrow N_t. Although the main goal is correct (maximize the model performance), the size of the feature subset is also maximized, and this is again incorrect. Therefore, in my understanding the correct objective function for feature selecture using pyswarms should be:
\alpha(1-P)+(1-\alpha)(\frac{N_f}{N_t})%2B(1-%5Calpha)(%5Cfrac%7BN_f%7D%7BN_t%7D))

**Comment by ljvmiranda921** [comment]
@diegoroman17 Gotcha! Would you mind updating the notebook as well, i.e., the implemented objective function, into the correct one? And rerun all cells so that the results would be consistent to the stated objective function

**Comment by diegoroman17** [comment]
@ljvmiranda921 , Yes, the entire notebook should be rerun with the modified objective function

**Comment by ljvmiranda921** [comment]
@diegoroman17 can you please do the rerun for us in order to complete this PR? Thanks!

**Comment by diegoroman17** [comment]
@ljvmiranda921 sure! I submitted a second commit with the entire notebook updated in this PR. Also, I attached the notebook below.
[feature_subset_selection.zip](https://github.com/ljvmiranda921/pyswarms/files/4669240/feature_subset_selection.zip)

**Comment by ljvmiranda921** [comment]
Thanks for this PR @diegoroman17 ! Congrats on your first contribution!
@all-contributors please add @diegoroman17 for docs

**Pull request merged**
