### PR TITLE
Fix parmameter doesn't match

### PR DESCRIPTION
**Pull request by Kutim**
## Description

Fix:

when i use "RandomSearch" with parmameter "bounds", the class "SearchBase" method "generate_score" has a issue:
```
parmameter "self.vclamp" will be assign to parmameter "bh_strategy" in the "optimizer" ,
such as class "GlobalBestPSO",class "GeneralOptimizerPSO" and class "LocalBestPSO".
```
Should use python keyword argument to fix it 

use python keyword argument to change 
```python
# pyswarms/utils/search/base_search.py line:101

self.n_particles, self.dims, options, self.bounds, self.vclamp
```
to 
```python
self.n_particles, self.dims, options, self.bounds, velocity_clamp=self.vclamp
```

## Motivation and Context

Bug fix

## How Has This Been Tested?

```python
g = RandomSearch(GlobalBestPSO, n_particles=n_particles, dimensions=dimensions,
                 options=options, objective_func=targetfunction, iters=5, n_selection_iters=3, bounds=bounds)

best_score, best_options = g.search()
```
## Screenshots (if appropriate):
The error I encountered is as follows：

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
Hi @Kutim ! Welcome to PySwarms! Let me review this next week :+1:

**Comment by ljvmiranda921** [comment]
Hi @whzup does this check-out? This involves the boundary-handling strategies

**Comment by whzup** [comment]
Hello @Kutim, thank you for your PR. Could you please change the base of your branch to the master branch? This PR includes commits which are part of the development branch. I'll have a look as soon as you have cleaned this one up. :+1: :smile:

**Comment by Kutim** [comment]
Sorry, I used the wrong branch.Please ignore it.
Please use the [PR#328](https://github.com/ljvmiranda921/pyswarms/pull/328)

**Comment by ljvmiranda921** [comment]
Closing this because the other PR has already been merged

**Pull request closed without merging**
