### PR TITLE
[WIP] Add Jupyter Notebook to visualise topologies

### PR DESCRIPTION
**Pull request by whzup**
## Description

This is a Jupyter notebook with animations of different topologies and some general information about the topologies themselves.

## Related Issue

#156 

## Motivation and Context

The goal of this PR is to visualise the differences between the topologies that have been implemented so far. Additionally, it provides another resource where one might look up how to use the `pyswarms` library. A Jupyter notebook is added where animations of different topologies are shown so one can compare the different neighbourhood properties visually.

## How Has This Been Tested?

**TBD**

## Screenshots (if appropriate):
**TBD**

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

**TBD**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by whzup** [comment]
@ljvmiranda921 could you check if you get the same error as I did? I copied the necessary bits from the `visualise` example and installed `ffmpeg` I have no idea what this error message means. Maybe you know a quick fix for that :anguished:

**Comment by ljvmiranda921** [comment]
It would be helpful if you can paste the whole traceback in this conversation, because diffs change:

```
INFO:matplotlib.animation:Animation.save using <class 'matplotlib.animation.FFMpegWriter'>
INFO:matplotlib.animation:MovieWriter.run: running command: ['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '720x576', '-pix_fmt', 'rgba', '-r', '12.5', '-loglevel', 'quiet', '-i', 'pipe:', '-vcodec', 'h264', '-pix_fmt', 'yuv420p', '-y', '/tmp/tmpjfc80jm5.m4v']
INFO:matplotlib.animation:MovieWriter -- Error running proc:
b''
b''
``

Traceback

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-98fc35d22b0a> in <module>()
      3 topology = top.Star()
      4 
----> 5 plot_optimization(options, topology)

<ipython-input-4-ac035cf64f85> in plot_optimization(options, topology)
     33 
     34     # Enables us to view it in a Jupyter notebook
---> 35     HTML(animation.to_html5_video())
     36     HTML(animation3d.to_html5_video())

/usr/lib64/python3.6/site-packages/matplotlib/animation.py in to_html5_video(self, embed_limit)
   1351                                 bitrate=rcParams['animation.bitrate'],
   1352                                 fps=1000. / self._interval)
-> 1353                 self.save(f.name, writer=writer)
   1354 
   1355             # Now open and base64 encode

/usr/lib64/python3.6/site-packages/matplotlib/animation.py in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
   1198                         # TODO: See if turning off blit is really necessary
   1199                         anim._draw_next_frame(d, blit=False)
-> 1200                     writer.grab_frame(**savefig_kwargs)
   1201 
   1202         # Reconnect signal for first draw if necessary

/usr/lib64/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

/usr/lib64/python3.6/site-packages/matplotlib/animation.py in saving(self, fig, outfile, dpi, *args, **kwargs)
    239             yield self
    240         finally:
--> 241             self.finish()
    242 
    243 

/usr/lib64/python3.6/site-packages/matplotlib/animation.py in finish(self)
    365     def finish(self):
    366         '''Finish any processing for writing the movie.'''
--> 367         self.cleanup()
    368 
    369     def grab_frame(self, **savefig_kwargs):

/usr/lib64/python3.6/site-packages/matplotlib/animation.py in cleanup(self)
    403     def cleanup(self):
    404         '''Clean-up and collect the process used to write the movie file.'''
--> 405         out, err = self._proc.communicate()
    406         self._frame_sink().close()
    407         _log.debug('MovieWriter -- Command stdout:\n%s', out)

/usr/lib64/python3.6/subprocess.py in communicate(self, input, timeout)
    841 
    842             try:
--> 843                 stdout, stderr = self._communicate(input, endtime, timeout)
    844             finally:
    845                 self._communication_started = True

/usr/lib64/python3.6/subprocess.py in _communicate(self, input, endtime, orig_timeout)
   1503                     selector.register(self.stdin, selectors.EVENT_WRITE)
   1504                 if self.stdout:
-> 1505                     selector.register(self.stdout, selectors.EVENT_READ)
   1506                 if self.stderr:
   1507                     selector.register(self.stderr, selectors.EVENT_READ)

/usr/lib64/python3.6/selectors.py in register(self, fileobj, events, data)
    349 
    350         def register(self, fileobj, events, data=None):
--> 351             key = super().register(fileobj, events, data)
    352             poll_events = 0
    353             if events & EVENT_READ:

/usr/lib64/python3.6/selectors.py in register(self, fileobj, events, data)
    235             raise ValueError("Invalid events: {!r}".format(events))
    236 
--> 237         key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
    238 
    239         if key.fd in self._fd_to_key:

/usr/lib64/python3.6/selectors.py in _fileobj_lookup(self, fileobj)
    222         """
    223         try:
--> 224             return _fileobj_to_fd(fileobj)
    225         except ValueError:
    226             # Do an exhaustive search.

/usr/lib64/python3.6/selectors.py in _fileobj_to_fd(fileobj)
     37         except (AttributeError, TypeError, ValueError):
     38             raise ValueError("Invalid file object: "
---> 39                              "{!r}".format(fileobj)) from None
     40     if fd < 0:
     41         raise ValueError("Invalid file descriptor: {}".format(fd))

ValueError: Invalid file object: <_io.BufferedReader name=61>
````

**Comment by ljvmiranda921** [comment]
@whzup do you already have `ffmpeg` installed?

**Comment by ljvmiranda921** [comment]
Works for me though.

Also, it turns out that the `HTML()` method should be used outside the `plot_optimization()` method. So what I did was have `plot_optimization()` return `animation` and `animation3d`, and call `HTML()` on them separately (in different cells). 

screenshot from 2018-08-22 09-57-39
screenshot from 2018-08-22 09-57-56

**Comment by whzup** [comment]
Hmm, in the links you provided the people use CentOS I actually use OpenSUSE. I reinstalled ffmpeg and included it in the path using `export PATH=$PATH:`. Moving the HTML() functions out of the function didn't change anything either :confused:

**Comment by ljvmiranda921** [comment]
Have you tried the SO solution above? They're both linux so they should complement.
It says that you may be missing `--enable-gpl --enable-libx264`. You already have `--enable-gpl`. Now do you have `--enable-libx264`? Check the config you copy-pasted :+1: 

I'm clueless after that. Try some workarounds:
- http://louistiao.me/posts/notebooks/embedding-matplotlib-animations-in-jupyter-notebooks/
- https://stackoverflow.com/questions/43445103/inline-animations-in-jupyter/43447370
- https://stackoverflow.com/questions/13316397/matplotlib-animation-no-moviewriters-available/14574894#14574894

Then set this: `rc('animation', html='html5')`

**Comment by whzup** [comment]
I'm reinstalling `FFmpeg` at the moment let me see if this works. Gonna keep you posted 👍

**Comment by whzup** [comment]
It works now 👍 Thanks for the help!

**Comment by whzup** [comment]
screenshot
I found this very weird behaviour that the 4 particles on the right side don't even move for a huge part of the optimization process. Do you think this is related to the boundaries issue?

**Comment by ljvmiranda921** [comment]
> I found this very weird behaviour that the 4 particles on the right side don't even move for a huge part of the optimization process. Do you think this is related to the boundaries issue #150? If so we urgently need the PR from them! 😮

Could be, but it’s usually for high dimensional search (we only have 2 dinensions). Many reasons exist: high cognitive param, inertia settings, etc. I suggest you continue with your PR first

**Comment by ljvmiranda921** [comment]
> Also, I think the best function to see the different behaviours might be the sphere function. What do you think?

Sphere is very easy, the particles might just move just like in the Star topology.

**Comment by ljvmiranda921** [comment]
Hmmm, work with what we have first. Won't an `ackley` function suffice?

**Comment by whzup** [comment]
@ljvmiranda921, sure! I'll go with the `holdertable`, though. It has some difficulty to it and doesn't cram the whole plot like some other functions do. :+1: The issue with the non-moving particles is very serious though! In every plot I've made so far there were particles that don't move at all!!!

**Comment by ljvmiranda921** [comment]
Understood. Can you help me investigate that? Things we can check:
- Check how the velocity matrix changes with respect to time. They're not moving probably because of zero-velocity. Let's first confirm if that's the case.
- Then, we can check if velocity updates correlate to global best and personal best positions as intended by the algorithm. Try a test swarm first and see if it's actually working

**Comment by ljvmiranda921** [comment]
> @ljvmiranda921, sure! I'll go with the holdertable

Problem with `holdertable` is that it's global minima is at the edges, kinda hard to see when visualizing it as a contour.

> It has some difficulty to it and doesn't cram the whole plot like some other functions do. 

Are you referring to `ackley`? Seems fine for me though

screenshot from 2018-08-24 09-57-06


@whzup Can you help me investigate that? Things we can check:
- Check how the velocity matrix changes with respect to time. They're not moving probably because of zero-velocity. Let's first confirm if that's the case.
- Then, we can check if velocity updates correlate to global best and personal best positions as intended by the algorithm. Try a test swarm first and see if it's actually working

**Comment by ljvmiranda921** [comment]
> The issue with the non-moving particles is very serious though! In every plot I've made so far there were particles that don't move at all!!! Even with different parameters!

@whzup Don't panic. Can you help me investigate that? Things we can check:
- Check how the velocity matrix changes with respect to time. They're not moving probably because of zero-velocity. Let's first confirm if that's the case.
- Then, we can check if velocity updates correlate to global best and personal best positions as intended by the algorithm. Try a test swarm first and see if it's actually working
- My guesses: some particles are stuck in local optima. But still there should be atleast a change to bring them out there.

**Comment by whzup** [comment]
> Your initial choice, ackley, seems fine for me though. Let's just stick with that.

I found that the `ackley` function was too similar to the sphere function in the sense that the particles are just pulled to the center and that we might not be able to distinguish the effects of the different topologies. But it's hard to tell with over half the swarm not moving at all :smile: 

>Can you help me investigate that?

Yes, I'll go ahead and check those :+1: !

**Comment by whzup** [comment]
Gonna work on this after we got #238 .

**Comment by ljvmiranda921** [comment]
I'll close this one for now. This is just a notebook so I think we can rebranch this from the new development branch (my bad). cc: @whzup

**Pull request closed without merging**
