### PR TITLE
Add objective functions (#158)

### PR DESCRIPTION
**Pull request by jayspeidell**
## Description
Objective Function Updates: Verified Goldstein and Booth functions working and removed TODO tags. Fixed Bulkin No 6 and removed TODO tag. Implemented Cross-in-Tray, Easom, Eggholder, Himmelblau's, Holder Table, and Three Hump Camel functions. File is getting long so I sorted the functions and added a list of functions and their corresponding function name to the docstring.

## Related Issue
Add more benchmark functions #158 

## Motivation and Context

More is better, right? 

## How Has This Been Tested?

I created a notebook with all the added functions and tested each function as I implemented it. All functions function in the full domain and visually match examples found online, and the minimums are what they should be. 

Then I used flask8 and black. I restricted flask8 and black testing to the file that I edited. 

I also ran py.test. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
Ok, this is good @jayspeidell !
I'll now leave you to @whzup :+1:

**Comment by jayspeidell** [comment]
I'll add the tests in tomorrow or Wednesday. I hadn't noticed that there were tests for the individual functions.

**Comment by jayspeidell** [comment]
Added tests for all the functions! Thanks for your patience, I know you've had to review this pull request a few times. I think I got it this time!

**Comment by Kosisochi** [comment]
Hello, how do I specify if I want to either maximize or minimize my objective function?

**Comment by whzup** [comment]
@Kosisochi If you have a question please open an issue and do not use closed issues for this purpose😅. By default, it minimizes the function if you put a negative sign to the cost function you find the maximum position.

**Pull request merged**
