### PR TITLE
updated the code in example notebooks as necessary to account for API…

### PR DESCRIPTION
**Pull request by Prathamesh99**
… changes

Made modifications in the optimize() method by removing some unexpected arguements

## Description
1. I have made some changes in the optimize() method by removing the unwanted parameters. The fx.sphere() function does not accept arguments such as "print_step" and "verbose". So, I removed them. 
2. Added a missing instance of Logistic regression "cl" in "feature_subset_selection notebook".

## Related Issue

#264

## Motivation and Context
The function sphere_func was replaced by sphere. These two functions have different parameters so necessary changes were made in the arguments of the sphere function.

## How Has This Been Tested?
I performed flake8, black and tox tests as mentioned in the contribution guide

## Screenshots (if appropriate):
image

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
Hi @Prathamesh99, thanks for your contribution!

Is it possible to revert all the black changes in the codebase? Having diffs in the notebooks is enough :) 

cc: @stevenbw, @whzup

**Comment by stevenbw** [comment]
Hi @Prathamesh99 , thanks for contributing!

I agree with @ljvmiranda921 , the initial aim was only to change the notebook. Even though the codebase may need altering I think it's beyond the scope of this issue and is too large a change for one PR.

**Comment by ljvmiranda921** [comment]
Reopen

**Comment by ljvmiranda921** [comment]
Hi @Prathamesh99 , unfortunately I will be overriding this PR to speed up documentation fixes. Thank you for your contribution, hoping to see you again!

**Pull request closed without merging**
