### PR TITLE
updated documentation (#297) for just `custom_optimization_loop.rst`

### PR DESCRIPTION
**Pull request by citomcclure**
Updated documentation to reflect API changes made on `custom_optimization_loop.ipynb` notebook. These changes were made in the `custom_optimization_loop.rst` file found in `docs/examples`

## Description
I added three code blocks (two inputs and one output) that were added into the jupyter notebook. These were the only changes in the updated notebook.

## Related Issue
This was done for issue #297 which followed the partial completion of issue #264 

## Motivation and Context
Updates documentation.

## How Has This Been Tested?
Have not tested yet, have been waiting to hear back from the collaborator on this issue. Not sure if documentation only changes require testing. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by citomcclure** [comment]
Hi @ljvmiranda921 ! I am a first-timer, and was wondering if I needed to run the tests for just documentation changes. It wasn't clear to me while reading through the CONTRIBUTING doc. Thanks!

**Comment by ljvmiranda921** [comment]
Hi, I think there's no need to run the test since you're doing docs. It's weird though that travis once cancelled. Sorry for the late reply!

**Comment by citomcclure** [comment]
Hi @stevenbw , I did in fact branch from the `master`. Good catch, thanks!

So I'll branch from `development` and then do a pull request back into `development` I presume? Does that mean I make a new pull request?

**Comment by citomcclure** [comment]
Hi @stevenbw , sorry, last question. I think the following text markdown should be removed from the documentation:

"We can see that the optimizer was able to find a good minima as shown above. You can control the `verbosity` of the output using the verbose argument, and the number of steps to be printed out using the `print_step` argument."

But it's still in the `basic_optimization` notebook. How do I proceed?

**Comment by stevenbw** [comment]
Hi @citomcclure ! Apologies for the delayed reply.

Yes, branch from `development` and you will need to open a new PR, but that's fine we can refer to and close this PR from the new one.

Don't worry about asking questions, I am happy to help :)

With regards to the outdated documentation - only update the notebook which you are working on for now. There will be a separate PR for updating the other notebooks. I'll check if `basic_optimization` is already being worked on.

**Comment by citomcclure** [comment]
Hi @stevenbw , in the link below two notebooks were changed. I had not realized this until I had switched to the `development` branch, so I did both. I can make separate pull requests though if you'd like. I have both done already.

https://github.com/ljvmiranda921/pyswarms/commit/fe1ffee63b184c0510797406dfe028c9d467c662

**Comment by stevenbw** [comment]
Hi @citomcclure , the work that was done in the link was to update the example notebooks. The work you have done is to update the .rst files to reflect the changes in the example notebooks, is that correct?

**Comment by citomcclure** [comment]
Hi @stevenbw , yes, that is correct.

**Comment by stevenbw** [comment]
Hi @citomcclure , if you push your changes I will take a look :smile:

**Comment by stevenbw** [comment]
Closed by #313

**Pull request closed without merging**
