### PR TITLE
Updated sample code to new API

### PR DESCRIPTION
**Pull request by ndngo**
## Description
Updated sample code in the README to work with the new API

## Related Issue
https://github.com/ljvmiranda921/pyswarms/issues/287

## Motivation and Context
The API changed so the code samples in the README needed to be updated to conform to the new API.

## How Has This Been Tested?
The code samples were tested by running the code and ensuring that the results are similar to the expected results before the API change. The testing environment was Python 3 on Windows Subsystem for Linux. Each code sample was executed and the output was compared to expected output shown in the README.

## Screenshots (if appropriate):
Swarm visualization
test
test1
test2

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
Hi @ndngo ! Thank you for your contribution! 

Some small updates from you before we merge your branch:
- I think it would be better to remove the **Dependencies** section. Since we have `requirements.txt`, there's no need for that anymore
- The way we represent the output as seen in the README:

```
>>> 2017-10-03 10:12:33,859 - pyswarms.single.global_best - INFO - Iteration 1/100, cost: 0.131244226714
>>> 2017-10-03 10:12:33,878 - pyswarms.single.global_best - INFO - Iteration 26/100, cost: 1.60297958653e-05
>>> 2017-10-03 10:12:33,893 - pyswarms.single.global_best - INFO - Iteration 51/100, cost: 1.60297958653e-05
>>> 2017-10-03 10:12:33,906 - pyswarms.single.global_best - INFO - Iteration 76/100, cost: 2.12638727702e-06
>>> 2017-10-03 10:12:33,921 - pyswarms.single.global_best - INFO - ================================
Optimization finished!
Final cost: 0.0000
Best value: [-0.0003521098028145481, -0.00045459382339127453]
```

Is now outdated. Currently we have a progress bar showing up. I'm wondering how we can show that. Maybe a GIF using [ASCIInema](https://asciinema.org/) might help?

**Comment by ndngo** [comment]
@ljvmiranda921 I've removed the dependencies section and added a gif showing the progress bar.

**Comment by ljvmiranda921** [comment]
Hi @ndngo sorry for the late reply! Got busy at work!

Let me check this one on Sunday, unless @stevenbw beats me into it!

**Comment by ljvmiranda921** [comment]
Merged! Thank you for your contribution @ndngo !

**Comment by ljvmiranda921** [comment]
@all-contributors please add @ndngo  for documentation

**Comment by ljvmiranda921** [comment]
Woops, another one.  @all-contributors please add @ndngo for documentation

**Comment by ljvmiranda921** [comment]
Woops another one, @all-contributors please add @ndngo for documentation

**Comment by iconoclast007** [comment]
Does pyswam do multiobjective?  Would love to see a user-defined multiobective problem, say 2 and then 3 variables

**Pull request closed without merging**
