### PR TITLE
Fix plotters documentation

### PR DESCRIPTION
**Pull request by ljvmiranda921**

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
Any more places I forgot to put the docs? cc: @whzup

**Comment by ljvmiranda921** [comment]
> As far as I'm concerned we don't have a plot_trajectory_2d function.

Thanks for catching. I also forgot that we need to update the `README.md` so that it's obvious that the limits should be exposed. How do you suggest we go about that?

**Comment by whzup** [comment]
We could change it from this:
> We can also plot the animation...
> ```python
> from pyswarms.utils.plotters.formatters import Mesher
> from pyswarms.utils.plotters.formatters import Designer
> # Plot the sphere function's mesh for better plots
> m = Mesher(func=fx.sphere_func)
> # Adjust figure limits
> d = Designer(limits=[(-1,1), (-1,1), (-0.1,1)],
>              label=['x-axis', 'y-axis', 'z-axis'])
> ```
> In 2D,
> ```python
> plot_contour(pos_history=optimizer.pos_history, mesher=m, mark=(0,0))
> ```

to that:
> We can also plot the animation...
> ```python
> from pyswarms.utils.plotters.formatters import Mesher
> from pyswarms.utils.plotters.formatters import Designer
> # Plot the sphere function's mesh for better plots
> m = Mesher(func=fx.sphere_func,
>            **limits=[(-1,1), (-1,1)])**
> # Adjust figure limits
> d = Designer(limits=[(-1,1), (-1,1), (-0.1,1)],
>              label=['x-axis', 'y-axis', 'z-axis'])
> ```
> In 2D,
> ```python
> plot_contour(pos_history=optimizer.pos_history, mesher=m, **designer=d**, mark=(0,0))
> ```

The new code is marked with two asterisks*

**Comment by ljvmiranda921** [comment]
I will do an override here, OK? So that you don't have to wait for me whenever you want to start the boundary feature :+1:

**Pull request merged**
