### PR TITLE
Changes made to basic_optimization.ipynb notebook for new API

### PR DESCRIPTION
**Pull request by fluencer**
- wherever the single_obj.sphere function is called, only `iter` argument is given, arguments `print_step` and `verbose` are removed.

## Motivation and Context
If this checks out I will make similar changes to other notebooks. Since I am a first-timer I am just changing one file to make sure I am doing it right.

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
Hi @fluencer ! Yup this one definitely checks out. You can proceed with the other notebooks. Just commit them here as usual!

**Comment by ljvmiranda921** [comment]
Hi @fluencer , ok, let me check on this in a while

**Comment by fluencer** [comment]
> Hi @fluencer , ok, let me check on this in a while, will merge hopefully by this weekend!

Thank you for all the help and guidance @ljvmiranda921 :)

**Comment by ljvmiranda921** [comment]
Merged to `development` branch, thank you for your contribution @fluencer!

**Comment by ljvmiranda921** [comment]
@all-contributors please add @fluencer for examples and doc

**Comment by konu90** [comment]
First of all thank you for your library, i will play this days with it.
But you should change the tutorials and docs, since these use the options "print step" and "verbose" and these options have been eliminated and the most basic tutorial fails (why I ended here ^^) But eliminating these options in the call to optimize method everything works correctly.
And im sorry if it was not the right place to post this, but I did not find another way to contact.

**Comment by ljvmiranda921** [comment]
Hi @konu90 , yes you are correct. There have been a lot of changes already and we didn't have time to redo the documentation. Thanks for the heads up!

**Pull request merged**
