### PR TITLE
Added documentation for options handler

### PR DESCRIPTION
**Pull request by nikhil-sethi**
Added documentation for options handler

## Description
- Updated tutorials.rst.
- Added equations and default arguments for all strategies in OptionsHandler.
- Moved some sentences around on the handlers page to make sense of new additions.

## Related Issue
NA

## Motivation and Context
It's documentation!

## How Has This Been Tested?
Tested the documentation with a complete sphinx build from scratch

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Apologies for the redundant commits. Forgot to rebase.

### CODE REVIEW

**Review by ljvmiranda921 — APPROVED** [review]

**Comment by Thothore** [comment]
pls merge :) I had a hard time figuring out how to use these options properly

**Comment by nikhil-sethi** [comment]
Hey @Thothore. I hope the documentation+examples were simple yet comprehensive enough. Let me know if you'd like more anything to be added!

**Comment by Thothore** [comment]
> Hey @ljvmiranda921. Is there anything stopping this merge that I'm missing?
> Also @Thothore, I hope the documentation+examples were simple yet comprehensive enough. Let me know if you'd like anything more to be added!

Maybe adding links to the [description of the handlers](https://pyswarms.readthedocs.io/en/latest/api/pyswarms.backend.html#pyswarms.backend.handlers.OptionsHandler) in the list of parameters of the [optimizers](https://pyswarms.readthedocs.io/en/latest/api/pyswarms.single.html#pyswarms.single.global_best.GlobalBestPSO.oh_strategy). It would help having an overview of what's possible without diving into the code (or at leats it's what I had to do) but this is not only about oh_strategy

**Comment by ljvmiranda921** [comment]
Thanks for following up! I really thought I've merged this already beforr

**Pull request merged**
